---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pizza
  labels:
    app: pizza-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-app-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: pizza-app-backend
    spec:
      containers:
      - name: backend-container
        image: shahdabdulaziz/pizza-app-backend2  
        ports: 
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://my-mongo:27017/menu"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector: 
    app: pizza-app-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32702   
  type: LoadBalancer

 
---
