apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pizza-pvc
  namespace: pizza
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 2Gi
