apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pizza-pvc
  namespace: pizza
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pizza-pv



