apiVersion: v1
kind: Service
metadata:
  name: my-mongo
  namespace: pizza
  labels:
    app: my-mongo
spec:
  selector:
    app: my-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer 
